# Details of this action see: https://github.com/golangci/golangci-lint-action
name: golangci-lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Use latest version of golangci-lint
          version: latest
